#cloud-config

users:
  - default
  - name: ii
    gecos: ii am Humacs
    primary_group: ii
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, docker
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDfOBYW4JREdUNAUY7k/XWKzH4pdx5GI+IfI67iyak7dvnv0sk3mfVHtNounEQuwW06vRiYLmKAG6BP4i97uvNVfoOIOdUSoaqiM/Q3OMPNUykKqh3kliMgX/tJJEsC27HtiDxrkxmgXbflE/JKc+3pSAYsjJkbeWUb2jmcpH8N2OpxeOLLOUeqZfQNsXVXUbfWFK2IcXUJNXUbuzZ4GiLifEoUfppD37e7V3HpNF+zDFim+5g/CYhqfrmlJ1ZCP2UG2Y8AVHl4N4NP2VHXvhl1dU7GkulU+cBA3BV/WF2e8J3cQCl+OFfRmztGeG4xKQPacNjE73bYI14jTSLOqcvhjwMFkr8t0MUCxmlDj1Nua6f3Js7Ft0zILpI20A4stV7h8f41VIehtNL4O+S21ps5dXz8UWcw90RZOmLSp6FPjFpedGqZcBH8ytMyGFiT4eag3SKQeIjNK2mgeaLqZOD+sEqRVWaQ89EX/loliep53cspa6a6hCUfW7WNuJqBtIUv+z9jfdT+Hv6TiLCQ82uQEhEr1KiWgOfNO7auds1cEoippoxnG9q9+Acw6Fe8laK3L3blHHatjxuMAn4Fp5N5GKBh/GxKMhf1CbMET3Q8HkgkuQqN5pXT+aR/517PYfXTMoGFZHWd87HBGg2MdpxBFnZ5LiqV0ByJvvuigh6C7w== caleb@titanlt
      - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEAsUXHYuDzE6fs2KkCj91qSqpMXyxozb9gDKcx3mlh87hCegevld75gQAhujVYGRgJLsdf7W0/lX81clCRP1FjbaYYrPkVWGR291U6K5rkL9kZqd9dC0h9iCvFTKdKC7sA/uaolFPWav3QFWdEp3geNNuAm/NKSckUs9yGgr1inANQNsHFl0JFzU34D2Kt43rKA0Qz3kkDKCnXzl+wltIKq5f1SH1HDlv0hoLgikVwg5CLLKCsZ8IFuxur1pdb26uM0vtFp2LJUNad6hK8RsU6p/NeTtOLjbKGsLkqCgSvoPxCAIbFKWIRuAfGd6CrNc2kAD4qM45jAvI9dLuzbopVfhXS16F0i3EzL8/VWuCk7l2mYRdjHAy+9fJksx1zx2wfeEXSoSUX8/ROxpWZaDA8gLAxUrp/hqHU351QDDEdunMfmlrGc6ixyIaxMugRuNsNB4eY91mmbiljeoSCs1GFbVRhC8KejdKpo266hSDdS7f1sV9dnxVhHBhCxWzN7+mfk4KzpjEVFoDR73X8IUOLGFikORl918i86bH2uqJ5zZLvOA4a0BqaRIExmAi7wQrm4iLcDH3THMpvEuy4965JZz1uPJYtGBD/Zj1O2sMA8K6zvSB/8q86fe1VdwIJxOHh50HqAH1jPHHfkxIdrL4nBmvF9Pkzpg/OWlyVjqWmWj0= hh
    shell: /bin/bash
    lock_passwd: false

timezone: Pacific/Auckland

package_update: true
package_upgrade: true
packages:
  - emacs-nox
  - tree
  - iproute2
  - net-tools
  - tcpdump
  - htop
  - iftop
  - tmux
  - tmate
  - bash-completion
  - less
  - xz-utils
  - sudo
  - curl
  - psmisc
  - whowatch
  - ca-certificates
  - libcap2-bin
  - git
  - openssh-client
  - postgresql-client-12
  - jq
  - inotify-tools
  - xtermcontrol
  - nodejs
  - gnupg2
  - tzdata
  - wget
  - python3-dev
  - xz-utils
  - apache2-utils
  - sqlite3
  - silversearcher-ag
  - build-essential
  - vim
  - rsync
  - unzip
  - iputils-ping
  - file
  - docker.io

runcmd:
  - set -x
  # kind and kubectl are our main requirements
  - |
    curl -Lo /usr/local/bin/kind \
      https://github.com/kubernetes-sigs/kind/releases/download/v0.8.1/kind-$(uname)-amd64
    chmod +x /usr/local/bin/kind
    curl -Lo /usr/local/bin/kubectl \
      https://storage.googleapis.com/kubernetes-release/release/v1.18.8/bin/linux/amd64/kubectl
    chmod +x /usr/local/bin/kubectl
  # - curl -Lo /usr/local/bin/kubectl https://github.com/humacs/humacs/releases/download/0.0.1-alpha/kubectl
  # tmate, helm, go, bazel, and the k8s src are needed for development
  # but can be deferred to the background
  - |
    (
      curl -L https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz \
      | tar --directory /usr/local/bin --extract --xz --strip-components 1 tmate-2.4.0-static-linux-amd64/tmate
      curl -L https://get.helm.sh/helm-v3.3.0-linux-amd64.tar.gz \
      | tar --directory /usr/local/bin --extract -xz --strip-components 1 linux-amd64/helm
      curl -L https://dl.google.com/go/go1.15.linux-amd64.tar.gz \
      | tar --directory /usr/local --extract --ungzip
      /bin/env GOCACHE=/usr/local/go/cache GO111MODULE=on GOPATH=/usr/local/go \
        /usr/local/go/bin/go get golang.org/x/tools/gopls@latest
      /bin/env GOCACHE=/usr/local/go/cache GO111MODULE=on GOPATH=/usr/local/go \
        /usr/local/go/bin/go get -u github.com/stamblerre/gocode
      curl -Lo /usr/local/bin/bazel \
        https://github.com/bazelbuild/bazel/releases/download/2.2.0/bazel-2.2.0-linux-x86_64
      chmod +x /usr/local/bin/bazel
      su ii -c 'bazel';
      su ii -c 'git clone https://github.com/kubernetes/kubernetes ~/kubernetes';
    ) 2>&1 > /var/log/cloud-init-background.log &
  - su ii -c 'echo export "PATH=\$PATH:/usr/local/go/bin" >> ~/.bashrc'
  - su ii -c 'git clone --recursive https://github.com/humacs/humacs ~/humacs'
  - su ii -c 'cd ~/humacs && ./install.sh'
  - su ii -c 'cd ~/humacs && cp .tmate.conf ~/ && cp tmux.conf ~/ && cp .gitconfig ~/'
  - su ii -c 'git clone https://github.com/cncf/apisnoop ~/apisnoop'
  - su ii -c 'cd ~/humacs/kind-configs && kind create cluster --config kind-config.yaml --image kindest/node:v1.19.0'
  - su ii -c 'kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml'
  - su ii -c 'echo Waiting for nginx-ingress && kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=90s'
  - su ii -c 'cd ~/apisnoop && export CURRENT_IP=127.0.0.1 NEW_IP=$(curl -4 ifconfig.co) && sed -i s:$CURRENT_IP:$NEW_IP:g kustomize/*yaml'
  - su ii -c 'cd ~/apisnoop && kubectl apply -k kustomize'
  - su ii -c 'kubectl -n apisnoop wait pod --for=condition=ready --selector=io.apisnoop.db=postgres --timeout=90s'
  - su ii -c 'kubectl -n apisnoop port-forward svc/postgres 5432 2>&1 > /dev/null' &
  - su ii -c 'curl -L https://github.com/humacs/humacs/releases/download/0.0.1-alpha/spacemacs-elpa-cache-2020.08.28.tgz | tar xvzfC - ~/humacs/spacemacs'
  - su ii -c 'cd && emacs -batch -l ~/.emacs'
  - su ii -c 'touch ~/.cloud-warnings.skip'

output:
  all: '| tee -a /var/log/cloud-init-output.log'
